import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "./reset.css"
import { cookies } from "next/headers";
const mainFont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SWAPI Indexed Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
  const dataTheme = cookieStore.get('data-theme')?.value ?? 'light'

  return (
    <html lang="en">
      
      <body data-theme={dataTheme} className={mainFont.className}>
        {children}
        </body>
    </html>
  );
}
