import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "./reset.css"
const mainFont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SWAPI Indexed Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body data-theme="dark" className={mainFont.className}>
        {children}
        </body>
    </html>
  );
}
